language: java
jdk:
- oraclejdk8
- oraclejdk7
before_install:
- wget "https://github.com/ZodiacEFZ/wpilib-robot-dependency/raw/master/libs/navx_frc.jar" -P libs
- wget "https://github.com/ZodiacEFZ/wpilib-robot-dependency/raw/master/libs/WPILib.jar" -P libs
- wget "https://github.com/ZodiacEFZ/wpilib-robot-dependency/raw/master/libs/NetworkTables.jar" -P libs
- chmod +x gradlew
script:
- gradle build
